export const FETCH_USER = 'fetch_user'
export const LOGOUT_USER = 'logout_user'
export const FETCH_POSTS = 'fetch_posts'
export const EDIT_POST = 'edit_posts'
export const CLEAR_EDIT = 'clear_edit'
export const EDIT_COMMENT = 'edit_comment'
export const CLEAR_EDIT_COMMENT = 'clear_edit_comment'